include:
  - remote: "https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/b61a03cabbf308e81289f7aaaf0b5a80a34ffb99/templates/fedora.yml"

build:
  before_script:
    - dnf install python3-pip wget unzip -y
    - pip3 install --break-system-packages opentype-feature-freezer
    - wget https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip
    - if $( ! echo "ff970a5d4561a04f102a7cb781adbd6ac4e9b6c460914c7a101f15acb7f7d1a4 Inter-4.0.zip" | sha256sum --check --status ); then exit 1; fi
  script:
    - unzip Inter-4.0.zip
    - pyftfeatfreeze --features "ss02" --replacenames "Inter Variable/GNOME UI" InterVariable.ttf GNOMEUI.ttf
  artifacts:
    paths:
      - GNOMEUI.ttf
