include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: release
      tarball-artifact-path: ${TARBALL_ARTIFACT_PATH}

stages:
  - build
  - release

variables:
  MESON_BUILD_DIR: build
  TARBALL_ARTIFACT_PATH: ${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz

image: quay.io/gnome_infrastructure/gnome-build-meta:core-nightly

build:
  stage: build
  script:
    - meson setup --prefix=/usr ${MESON_BUILD_DIR}
    - meson install -C ${MESON_BUILD_DIR}
  artifacts:
    paths:
      - ${MESON_BUILD_DIR}

release:
  stage: release
  script:
    - meson dist -C ${MESON_BUILD_DIR}
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}
    when: always
    paths:
      - ${TARBALL_ARTIFACT_PATH}
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
