include:
  - remote: https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: release
      tarball-artifact-path: ${TARBALL_ARTIFACT_PATH}

stages:
  - build
  - release

variables:
  TARBALL_ARTIFACT_PATH: ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz

sans:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False python3-pip wget unzip make
  script:
    - pip install --root-user-action ignore opentype-feature-freezer
    - sans/update-fonts.sh
    - make sans
  artifacts:
    paths:
      - sans/AdwaitaSans-Regular.ttf
      - sans/AdwaitaSans-Italic.ttf

mono:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False nodejs-npm ttfautohint make git
    - git submodule update --init --depth 1
  script:
    - npm install --prefix mono/Iosevka
    - make mono
  artifacts:
    paths:
      - mono/AdwaitaMono-Regular.ttf
      - mono/AdwaitaMono-Italic.ttf
      - mono/AdwaitaMono-Bold.ttf
      - mono/AdwaitaMono-BoldItalic.ttf

release:
  stage: release
  needs:
    - sans
    - mono
  script:
    - tar -cJf ${TARBALL_ARTIFACT_PATH} sans/AdwaitaSans-* sans/LICENSE.md mono/AdwaitaMono-* mono/LICENSE.md
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}
    when: always
    paths:
      - ${TARBALL_ARTIFACT_PATH}
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
