include:
  - remote: "https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml"

stages:
  - build

sans:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False python3-pip wget unzip make
  script:
    - pip install --root-user-action ignore opentype-feature-freezer
    - wget https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip
    - make sans
  artifacts:
    paths:
      - AdwaitaSans-Regular.ttf
      - AdwaitaSans-Italic.ttf

mono:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False nodejs-npm ttfautohint make git
    - git submodule update --init --depth 1
  script:
    - cd Iosevka
    - npm install
    - cd ..
    - make mono
  artifacts:
    paths:
      - AdwaitaMono-Regular.ttf
      - AdwaitaMono-Italic.ttf
      - AdwaitaMono-Bold.ttf
      - AdwaitaMono-BoldItalic.ttf
