include:
  - remote: "https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/b61a03cabbf308e81289f7aaaf0b5a80a34ffb99/templates/fedora.yml"

stages:
  - generate

generate:
  stage: generate
  script:
    - dnf install python3-pip wget unzip make -y
    - pip3 install --break-system-packages opentype-feature-freezer
    - wget https://github.com/rsms/inter/releases/download/v4.0/Inter-4.0.zip
    - make
  artifacts:
    paths:
      - GNOMEUI.ttf
      - GNOMEUI-Italic.ttf
