include:
  - remote: "https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml"

stages:
  - generate

generate:
  stage: generate
  script:
    - dnf install -y --setopt=install_weak_deps=False python3-pip wget unzip make
    - pip install --root-user-action ignore opentype-feature-freezer
    - wget https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip
    - make
  artifacts:
    paths:
      - GNOMEUI.ttf
      - GNOMEUI-Italic.ttf
