include:
  - remote: "https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml"

stages:
  - build

variables:
  INTER_VERSION: 4.1
sans:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False python3-pip wget unzip make
  script:
    - pip install --root-user-action ignore opentype-feature-freezer
    - wget https://github.com/rsms/inter/releases/download/v${INTER_VERSION}/Inter-${INTER_VERSION}.zip
    - mv Inter-${INTER_VERSION}.zip sans
    - make sans
  artifacts:
    paths:
      - sans/AdwaitaSans-Regular.ttf
      - sans/AdwaitaSans-Italic.ttf

mono:
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=False nodejs-npm ttfautohint make git
    - git submodule update --init --depth 1
  script:
    - npm install --prefix mono/Iosevka
    - make mono
  artifacts:
    paths:
      - mono/AdwaitaMono-Regular.ttf
      - mono/AdwaitaMono-Italic.ttf
      - mono/AdwaitaMono-Bold.ttf
      - mono/AdwaitaMono-BoldItalic.ttf
