FILES=AdwaitaMono-Regular.ttf \
	AdwaitaMono-Italic.ttf \
	AdwaitaMono-Bold.ttf \
	AdwaitaMono-BoldItalic.ttf

all: $(FILES)

install:
	install -Dm655 -t "$(DESTDIR)/$(PREFIX)/share/fonts/Adwaita" $(FILES)
